server:
  port: 2014
  servlet:
    context-path: /data
spring:
  profiles: default
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/db1?useSSL=false
    username: root
    password: P@ssw0rd
    type: org.springframework.jdbc.datasource.DriverManagerDataSource

hazelcast:
  cluster:
    addresses: localhost:5701,localhost:5702,localhost:5703
    name: cluster-name
    whitelistedClasses: cap.hazelcast.uday.HDMProject.domain.VodBeamDTO
  client:
    heartbeat:
      interval: 1000
      timeout: 5000
